### ISSUE TITLE
Chrome: Uncaught RangeError

### ISSUE THREAD

**Issue by fwebdev** [WebReflection/DOMContentLoaded#2]
Chrome is throwing an 

> Uncaught RangeError: Maximum call stack size exceeded.

For this line:

```
document[add] = function addEventListener(
```

when I try to add another EventListener like this one:

```
document.addEventListener('touchmove', jPar.navi.scroll.doScroll, false);
```

Anything I can do?

**Comment by WebReflection** [comment]
Shame of me I've put here the wrong version of the script … the updated one will work as you expect without creating stack problems. Apologies for the inconvenient.
