### ISSUE TITLE
Featuredetect addEventListener for old Browsers

### ISSUE THREAD

**Issue by fwebdev** [WebReflection/DOMContentLoaded#3]
You could add a Featuredetection like

```
if(document.addEventListener){....
```

Old IE8 does not know addEventListener nor "async" so we don't need your Script there. :-)

**Comment by WebReflection** [comment]
Let me introduce you http://github.com/WebReflection/ie8 ...the script every website should include conditionally at the top... It's pointless to ignore DOMContentLoaded as fixed here, if you don't want it fixed, don't use it ;-)

**Comment by WebReflection** [comment]
Actually, I'll just close this as non issue but feel free to ask more, if needed. Thanks
