### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by bjoerge** [WebReflection/DOMContentLoaded#4]
Hi,
this script has made my life so much easier and I now start almost every new project by including it. Thanks a lot for the effort!

It would be nice to be able to include it as a project dependency from npm instead of copying it all over. Would you mind adding a package.json and publish to npm?

**Comment by WebReflection** [comment]
if you bundle this script with anything else it might fails. As example, you bundle this via browserify and you load your bundle with `async` and goodbye functionality, it will not run as it should.

I think it would be wiser to put this directly in your most basic HTML template, would that work?

**Comment by WebReflection** [comment]
To be more precise, there is a reason I wrote this in [the source code](https://github.com/WebReflection/DOMContentLoaded/blob/master/DOMContentLoaded.js#L1-L5):

``` js
// DO NOT COPY AND PASTE IN ANY LIBRARY OR JS FILE
// this  MUST be the first script on top of **your** HTML page
// and it MUST be **included/executed only once**
// If your framework fix this already and every script in your page
// uses such framework then you don't need this script
```

**Comment by bjoerge** [comment]
Yeah, I'm aware of that. I'm thinking including it in the HTML template, something along the lines of:

``` js
var fs = require('fs')
var domContentLoadedSrc = fs.readFileSync(require.resolve('dom-content-loaded'))

//…

res.send(`<html><head><script>${domContentLoadedSrc}</script> …`)
```

**Comment by WebReflection** [comment]
I think that's a better approach, also because I wouldn't know exactly what to export as module.

I'll close this for now, if you have better ideas let me know. Thanks
